name: Run on pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  production_integration_tests_1:
    name: Production integration tests 1
    if: ${{ vars.TEST_VAR == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set new value for TEST_VAR
        run: echo "TEST_VAR=false" >> $GITHUB_ENV
      - name: Result
        run: echo "Completed"

  production_integration_tests_2:
    name: Production integration tests 2
    if: ${{ vars.TEST_VAR == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Result
        run: echo "Runned after tests_1"
